name: Code Quality
on:
  [pull_request, push]:
    branches:
      - main
    paths:
      - '.github/workflows/code-quality.yml'
    workflow_dispatch:
jobs:
  code-quality:
    runs-on: ubuntu-latest
    name: Code Quality
    steps:
      - name: GitHub Checkout
        uses: actions/checkout@v3

      - name: Node.js Configuration
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Install Dependencies
        run: npm install --ci

      - name: Run Unit Tests
        run: npm run test

      - name: Run ESLint
        run: npm run lint

      - name: Run Build System
        run: npm run build