name: Code Quality
on:
  pull_request:
    branches:
      - main
      - development
      - feature/**
      - feat/**
      - bugfix/**
      - fix/**
      - chore/**
      - release/**
      - beta/**
jobs:
  code-quality:
    runs-on: ubuntu-latest
    name: Setup
    steps:
      - name: GitHub Checkout
        uses: actions/checkout@v3

      - name: Node.js Configuration
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Install Yarn & Dependencies
        run: |
          npm i -g yarn
          yarn install --frozen-lockfile

      - name: Run Unit Tests
        run: yarn test

      - name: Run ESLint
        run: yarn lint

      - name: Run Build System
        run: yarn build