name: Code Quality
on:
  pull_request:
    branches:
      - main
      - development
      - feature/**
      - feat/**
      - bugfix/**
      - fix/**
      - chore/**
      - release/**
      - beta/**
    paths:
      - '.github/workflows/code-quality.yml'
jobs:
  code-quality:
    runs-on: ubuntu-latest
    name: Code Quality
    steps:
      - name: GitHub Checkout
        uses: actions/checkout@v3

      - name: Node.js Configuration
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Install Dependencies
        run: npm install --ci

      - name: Run Unit Tests
        run: npm run test

      - name: Run ESLint
        run: npm run lint

      - name: Run Build System
        run: npm run build